Novuscom\Bundle\CMFBundle\Entity\Element:
    type: entity
    table: null
    repositoryClass: Novuscom\Bundle\CMFBundle\Entity\ElementRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        code:
            type: string
            length: 255
            nullable: true
        preview_text:
            type: text
            length: 65535
            nullable: true
        detail_text:
            type: text
            length: 4294967295
            nullable: true
        last_modified:
            type: datetime
            nullable: true
        sort:
            type: smallint
            length: 4
            nullable: true
            options:
                default: 500
        active:
            type: boolean
        header:
            type: string
            length: 255
            nullable: true
        title:
            type: string
            length: 255
            nullable: true
        keywords:
            type: string
            length: 255
            nullable: true
        description:
            type: string
            length: 255
            nullable: true
    oneToOne:
        PreviewPicture:
            targetEntity: Novuscom\Bundle\CMFBundle\Entity\File
            joinColumn:
                name: preview_picture
                referencedColumnName: id
                onDelete: "CASCADE"
        DetailPicture:
            targetEntity: Novuscom\Bundle\CMFBundle\Entity\File
            joinColumn:
                name: detail_picture
                referencedColumnName: id
                onDelete: "CASCADE"
    manyToOne:
        block:
            targetEntity: Block
            inversedBy: element
            joinColumn:
                name: block_id
                referencedColumnName: id
                onDelete: "CASCADE"
    oneToMany:
        ElementProperty:
            targetEntity: ElementProperty
            mappedBy: element
            cascade: ["persist"]
        ElementPropertyF:
            targetEntity: ElementPropertyF
            mappedBy: element
            cascade: ["persist"]
        ElementPropertyDT:
            targetEntity: ElementPropertyDT
            mappedBy: element
            cascade: ["persist"]
        section:
            targetEntity: ElementSection
            mappedBy: element
            cascade: ["persist"]
    lifecycleCallbacks: {  }
