Novuscom\CMFBundle\Entity\ElementPropertyDT:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        property_id:
            type: integer
        description:
            type: string
            length: 600
            nullable: true
        value:
            type: datetime
    manyToOne:
        element:
            targetEntity: Element
            inversedBy: ElementPropertyDT
            joinColumn:
                name: element_id
                referencedColumnName: id
                onDelete: "CASCADE"
        property:
            targetEntity: Property
            inversedBy: ElementPropertyDT
            joinColumn:
                name: property_id
                referencedColumnName: id
                onDelete: "CASCADE"
    lifecycleCallbacks: {  }
