Novuscom\CMFBundle\Entity\File:
    type: entity
    table: null
    repositoryClass: Novuscom\CMFBundle\Entity\FileRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        original_name:
            type: string
            length: 255
        size:
            type: integer
        description:
            type: string
            length: 255
            nullable: true
        type:
            type: string
            length: '50'
        time:
            type: datetime
            nullable: true
    oneToMany:
        property:
            targetEntity: ElementPropertyF
            mappedBy: file
            cascade: ["persist"]
    lifecycleCallbacks: {  }
