parameters:
    locale: ru
    database_driver: pdo_mysql
# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        metadata_cache_driver: apcu
        query_cache_driver: apcu
        result_cache_driver: apcu
        #resolve_target_entities:
        #    CMF\PageBundle\Model\PageSubjectInterface: CMF\SiteBundle\Entity\Site
        dql:
            numeric_functions:
                Rand: Novuscom\CMFBundle\DQL\RandFunction
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                # make sure vendor library location is correct
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
            loggable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
            tree:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    always_authenticate_before_granting: true
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            #id: fos_user.user_provider.username
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            #form_login:
            #    provider: fos_userbundle
            #    csrf_provider: form.csrf_provider
            form_login:
                login_path: /admin_login/
                check_path: /login_check/
            logout:
                path:   /logout/
            anonymous:    true

    access_control:
        #- { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/efconnect, role: ROLE_USER }
        - { path: ^/elfinder, role: ROLE_USER }


# services to handle doctrine extensions
# import it in config.yml
services:
    # Doctrine Extension listeners to handle behaviors
    fos_user.doctrine_registry:
        alias: doctrine
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
            - [ setDefaultLocale, [ %locale% ] ]
            - [ setTranslationFallback, [ false ] ]

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.loggable:
        class: Gedmo\Loggable\LoggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]


knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: PAGE                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

fm_elfinder:
      instances:
        tinymce:
          locale: %locale%
          editor: tinymce4
          include_assets: true
          relative_path: true
          path_prefix: /
          fullscreen: true
          connector:
              debug: true # defaults to false
              binds:
                  upload.presave:
                      - Plugin.AutoResize.onUpLoadPreSave
              plugins:
                  AutoResize: # global resize options, applies to root which don't have his own resize configuraion
                      enable: true
                      maxWidth: 1920
                      maxHeight: 1080
                      quality: 95 # JPEG image save quality
              roots:       # at least one root must be defined
                  uploads:
                      driver: LocalFileSystem
                      path: upload/media
                      plugins:
                          AutoResize:
                              enable: true
                              maxWidth: 1920
                              maxHeight: 1080
                              quality: 95 # JPEG image save quality
                      upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'image/gif', 'application/pdf']
                      upload_deny: ['all']
                      upload_max_size: 1024M



stfalcon_tinymce:
    #base_url: /
    theme:
        simple:
            relative_urls: false
            file_browser_callback : elFinderBrowser
            image_class_list:
                - {title: 'без класса', value: ''}
                - {title: 'Слева', value: 'left-image'}
                - {title: 'Справа', value: 'right-image'}
                - {title: 'По ширине', value: 'img-fluid img-responsive'}
            content_css: "/admin/dist/tinymce/content.css"
            plugins:
                - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                - "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "insertdatetime media nonbreaking save table contextmenu directionality"
                - "emoticons template paste textcolor"
            toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
            toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
            image_advtab: true
            templates:
                - {title: 'Test template 1', content: 'Test 1'}
                - {title: 'Test template 2', content: 'Test 2'}
        advanced:
            plugins:
                - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                - "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "insertdatetime media nonbreaking save table contextmenu directionality"
                - "emoticons template paste textcolor"
            toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
            toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
            image_advtab: true
            templates:
                - {title: 'Test template 1', content: 'Test 1'}
                - {title: 'Test template 2', content: 'Test 2'}

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Novuscom\CMFUserBundle\Entity\User
    group:
        group_class: Novuscom\CMFUserBundle\Entity\Group
    registration:
        confirmation:
            enabled: true
            from_email: # Use this node only if you don't want the global email address for the confirmation email
                address:        averichev@yandex.ru
                sender_name:    Sender name
    #service:
    #  mailer: Novuscom_user.mailer.twig_swift

framework:
    esi: { enabled: true }
    #fragments:       { path: /_proxy }
    fragments: { path: /_fragment }
    #translator:      { fallback: %locale% }
    translator: ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true, enabled: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    assets:
    default_locale:  "%locale%"
    trusted_proxies:
        - 127.0.0.1
    session:
        save_path: %kernel.root_dir%/var/sessions
    #fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    #globals:
    #    Element: "@Element"
    paths:
        "%kernel.root_dir%/../templates/": templates
    form_themes:
        - 'NovuscomCMFBundle::bootstrap-form.html.twig'

# Assetic Configuration
#assetic:
#    debug:          %kernel.debug%
#    use_controller: false
#    bundles:        [ ]
#    #java: /usr/bin/java
#    filters:
#        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar



# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }


knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: pageNumber                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template


apy_breadcrumb_trail:
    template: CMFTemplateBundle:Default:crumbs.html.twig

liip_imagine:
    filter_sets:
        outbound:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        inset:
            quality: 75
            filters:
                thumbnail: { size: [800, 600], mode: inset }
        exact:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        proportional:
            quality: 75
            filters:
                thumbnail: { size: [800, 600], mode: inset }
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        my_inset:
            quality: 75
            filters:
                thumbnail: { size: [1920, 1080], mode: inset }

monolog:
    handlers:
        mail:
            type:         fingers_crossed
            # 500 errors are logged at the critical level
            action_level: critical
            # to also log 400 level errors (but not 404's):
            # action_level: error
            # excluded_404s:
            #     - ^/
            handler:      buffered
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: 'neokortex@mail.ru'
            to_email:   'averichev@yandex.ru'
            # or list of recipients
            # to_email:   ['dev1@example.com', 'dev2@example.com', ...]
            subject:    An Error Occurred!
            level:      debug