security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    always_authenticate_before_granting: true
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            #id: fos_user.user_provider.username
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            #form_login:
            #    provider: fos_userbundle
            #    csrf_provider: form.csrf_provider
            form_login:
                login_path: /login/
                check_path: /login/check/
            logout:
                path:   /logout/
            anonymous:    true

    access_control:
        #- { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/efconnect, role: ROLE_USER }
        - { path: ^/elfinder, role: ROLE_USER }