parameters:
    File.class:      Novuscom\CMFBundle\Services\File
    ElementsList.class:      Novuscom\CMFBundle\Services\ElementsList
    Crumbs.class:      Novuscom\CMFBundle\Services\Crumbs
    SectionClass:      Novuscom\CMFBundle\Services\SectionClass
    guzzle.client.class:  Guzzle\Service\Client
    page_class:      Novuscom\CMFBundle\Controller\DefaultController

services:
    cmf.twig.template_extension:
        class: Novuscom\CMFBundle\Twig\TemplateExtension
        tags:
            - { name: twig.extension }
        arguments: [@service_container, @logger]
    User:
        class:        Novuscom\CMFBundle\Services\User
        arguments: [ @service_container, @logger ]
    Site:
        class:        Novuscom\CMFBundle\Services\Site
        arguments: [ @service_container, @logger, @request_stack, @doctrine.orm.entity_manager ]
    File:
        class:        "%File.class%"
        arguments: [ @service_container ]
    Page:
        class:        Novuscom\CMFBundle\Services\Page
        arguments: [ @doctrine.orm.entity_manager, @logger, @Site ]
    Section:
        class:        Novuscom\CMFBundle\Services\Section
        arguments: [ @logger, @doctrine.orm.entity_manager ]
    Element:
        class:        Novuscom\CMFBundle\Services\Element
        arguments: [ @doctrine.orm.entity_manager, @logger ]
    Cart:
        class:        Novuscom\CMFBundle\Services\Cart
        arguments: [ @doctrine.orm.entity_manager, @logger, @request_stack, @service_container ]
    Product:
        class:        Novuscom\CMFBundle\Services\Product
        arguments: [ @doctrine.orm.entity_manager, @logger ]
    cmf_routing.routing_loader:
        class: Novuscom\CMFBundle\Routing\ExtraLoader
        tags:
            - { name: routing.loader }
        arguments: [@doctrine.orm.entity_manager, @logger]
    ElementsList:
        class:        "%ElementsList.class%"
        arguments: [ @doctrine.orm.entity_manager, @Element, @logger, @Section ]
    Crumbs:
        class:        "%Crumbs.class%"
        arguments: [ @doctrine.orm.entity_manager, @logger, @apy_breadcrumb_trail ]
    SectionClass:
        class:        "%SectionClass%"
        arguments: [@doctrine.orm.entity_manager]
    PageClass:
        class:        "%page_class%"
        calls:
            - [setContainer, ["@service_container"]]
    Guzzle:
        class: %guzzle.client.class%
        tags:
            - { name:guzzle.client }
        arguments: ["http://www.google.com/"]
    user_events_listener:
        class: Novuscom\CMFBundle\Event\UserSubscriber
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: user.register, method: onUserRegister }