#Novuscom\Bundle\CMFBundle\Entity\Site:
#    properties:
#        name:
#            - Ip: ~
#        alias:
#            - Email: ~

Novuscom\Bundle\CMFBundle\Entity\Alias:
#    constraints:
#        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
#    properties:
#        name:
#           - Ip: ~
#           - Novuscom\Bundle\CMFBundle\Validator\Constraints\Alias: ~