<?php

namespace Novuscom\Bundle\CMFBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRepository extends EntityRepository
{
    public function findBySites( $sites )
    {

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('m')
            ->from('NovuscomCMFBundle:Block', 'm')
            ->innerJoin('m.sites', 'e')
            ->where('e.id IN (:sites_id)' )
            ->setParameter('sites_id', array_keys($sites) )
            ->getQuery()
            ->getResult();
    }
}
