<?php

namespace Novuscom\CMFBundle\Repository;

/**
 * ElementPropertySectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementPropertySectionRepository extends \Doctrine\ORM\EntityRepository
{
}
