<?php

namespace Novuscom\CMFBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ElementSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementSectionRepository extends EntityRepository
{
}
