<?php

namespace Novuscom\CMFBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PropertyListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyListRepository extends EntityRepository
{
}
