<?php

namespace Novuscom\CMFBundle\Repository;

/**
 * SectionPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionPropertyRepository extends \Doctrine\ORM\EntityRepository
{
}
