<?php

namespace Novuscom\CMFBundle\Entity;

/**
 * StatusOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
