admin_property:
    pattern:  /
    defaults: { _controller: "NovuscomCMFBundle:Property:index" }

admin_property_show:
    pattern:  /{id}/show
    defaults: { _controller: "NovuscomCMFBundle:Property:show" }

admin_property_new:
    pattern:  /new
    defaults: { _controller: "NovuscomCMFBundle:Property:new" }

admin_property_create:
    pattern:  /create
    defaults: { _controller: "NovuscomCMFBundle:Property:create" }
    requirements: { _method: post }

admin_property_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "NovuscomCMFBundle:Property:edit" }

admin_property_update:
    pattern:  /{id}/update
    defaults: { _controller: "NovuscomCMFBundle:Property:update" }
    requirements: { _method: post|put }

admin_property_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "NovuscomCMFBundle:Property:delete" }
    requirements: { _method: post|delete }
