admin_property_index:
    path:     /
    defaults: { _controller: "NovuscomCMFBundle:Property:index" }
    methods:  GET

admin_property_show:
    path:     /{id}/show
    defaults: { _controller: "NovuscomCMFBundle:Property:show" }
    methods:  GET

admin_property_new:
    path:     /new
    defaults: { _controller: "NovuscomCMFBundle:Property:new" }
    methods:  [GET, POST]

admin_property_edit:
    path:     /{id}/edit
    defaults: { _controller: "NovuscomCMFBundle:Property:edit" }
    methods:  [GET, POST]

admin_property_delete:
    path:     /{id}/delete
    defaults: { _controller: "NovuscomCMFBundle:Property:delete" }
    methods:  DELETE
