admin_route:
    path:  /
    defaults: { _controller: "NovuscomCMFBundle:Route:index" }

admin_route_show:
    path:  /{id}/show
    defaults: { _controller: "NovuscomCMFBundle:Route:show" }

admin_route_new:
    path:  /new
    defaults: { _controller: "NovuscomCMFBundle:Route:new" }

admin_route_create:
    path:  /create
    defaults: { _controller: "NovuscomCMFBundle:Route:create" }
    requirements: { _method: post }

admin_route_edit:
    path:  /{id}/edit
    defaults: { _controller: "NovuscomCMFBundle:Route:edit" }

admin_route_update:
    path:  /{id}/update
    defaults: { _controller: "NovuscomCMFBundle:Route:update" }
    requirements: { _method: post|put }

admin_route_delete:
    path:  /{id}/delete
    defaults: { _controller: "NovuscomCMFBundle:Route:delete" }
    requirements: { _method: post|delete }
