admin_searchquery:
    pattern:  /
    defaults: { _controller: "NovuscomCMFBundle:SearchQuery:index" }

admin_searchquery_show:
    pattern:  /{id}/show
    defaults: { _controller: "NovuscomCMFBundle:SearchQuery:show" }

admin_searchquery_new:
    pattern:  /new
    defaults: { _controller: "NovuscomCMFBundle:SearchQuery:new" }

admin_searchquery_create:
    pattern:  /create
    defaults: { _controller: "NovuscomCMFBundle:SearchQuery:create" }
    requirements: { _method: post }

admin_searchquery_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "NovuscomCMFBundle:SearchQuery:edit" }

admin_searchquery_update:
    pattern:  /{id}/update
    defaults: { _controller: "NovuscomCMFBundle:SearchQuery:update" }
    requirements: { _method: post|put }

admin_searchquery_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "NovuscomCMFBundle:SearchQuery:delete" }
    requirements: { _method: post|delete }
