admin_system:
    pattern:  /
    defaults: { _controller: "NovuscomCMFBundle:System:update" }

admin_system_upgrade:
    pattern:  /upgrade
    defaults: { _controller: "NovuscomCMFBundle:System:upgrade" }
    methods:  [POST]