admin_system:
<<<<<<< HEAD
    path:  /
    defaults: { _controller: "NovuscomCMFBundle:System:update" }

admin_system_upgrade:
    path:  /upgrade
=======
    pattern:  /
    defaults: { _controller: "NovuscomCMFBundle:System:update" }

admin_system_upgrade:
    pattern:  /upgrade
>>>>>>> 525d180da3e2b35d6835ee702b951d4ef7e02637
    defaults: { _controller: "NovuscomCMFBundle:System:upgrade" }
    methods:  [POST]